### PR TITLE
Different default behavior for no SNI vs. no match

### PR DESCRIPTION
**Pull request by divergentdave**
The "default" option is removed and replaced with two new options, "fallback" and "wildcard." Any incoming connection without an SNI extension is sent to the first server configured with `fallback` set. If
an incoming connection does have an SNI extension, but the name is not recognized, then it is sent to the first server configured with `wildcard` set.

This implements #1

### CODE REVIEW

**Comment by paultag** [comment]
@divergentdave So, I dig this and as-is, I think it's good enough to deploy -- but a crazy idea; 

What if the same ends (what we're now calling `wildcard`) was actually a bit more -- perhaps a `regexp` `pattern`, and allow matching on hostname by `regexp.Match` -- so that you could set `.*\.onion` or something. Thoughts?

**Comment by divergentdave** [comment]
That wouldn't quite work, because Tor's front domains use normal TLDs. For example, my bridge's certificate is for CN=www.vdczjm2y.net and signed by a certificate for CN=www.nzaks7py5fplw.com.

If we threw out the `wildcard` flag, added an option to use regexp or glob patterns, and then defined that the server would use the first endpoint that matched, then that would work. We could then put the bridge at the bottom with a pattern of `*` or `.*`.

**Comment by paultag** [comment]
Fair enough!

On Mon, Dec 28, 2015 at 9:27 PM, David Cook notifications@github.com
wrote:

> That wouldn't quite work, because Tor's front domains use normal TLDs. For
> example, my bridge's certificate is for CN=www.vdczjm2y.net and signed by
> a certificate for CN=www.nzaks7py5fplw.com.
> 
> If we threw out the wildcard flag, added an option to use regexp or glob
> patterns, and then defined that the server would use the first endpoint
> that matched, then that would work. We could then put the bridge at the
> bottom with a pattern of \* or .*.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paultag/sniff/pull/2#issuecomment-167702064.

## 

:wq

**Comment by divergentdave** [comment]
Closing in favor of #3

**Pull request closed without merging**
